# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('video_name', models.CharField(max_length=200)),
                ('video_views', models.IntegerField(default=0)),
                ('video_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoapp.Video'),
        ),
    ]
