# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='group',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='parameter',
            new_name='town',
        ),
    ]
