# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170312_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=220),
        ),
    ]
