# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besttube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestvideo',
            name='name_video',
            field=models.CharField(default='abcd', max_length=200),
            preserve_default=False,
        ),
    ]
