# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besttube', '0002_bestvideo_name_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestvideo',
            name='name_video',
            field=models.TextField(),
        ),
    ]
