# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besttube', '0003_auto_20170318_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestvideo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bestvideo',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
