# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besttube', '0004_auto_20170318_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestvideo',
            name='best',
            field=models.CharField(help_text='url', max_length=200),
        ),
        migrations.AlterField(
            model_name='bestvideo',
            name='name_video',
            field=models.CharField(help_text='name video', max_length=200),
        ),
        migrations.AlterField(
            model_name='bestvideo',
            name='number_in',
            field=models.CharField(help_text='position in raiting', max_length=10),
        ),
    ]
