# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besttube', '0005_auto_20170319_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestvideo',
            old_name='name_video',
            new_name='video_name',
        ),
        migrations.RenameField(
            model_name='bestvideo',
            old_name='number_in',
            new_name='views_number',
        ),
        migrations.RemoveField(
            model_name='bestvideo',
            name='best',
        ),
        migrations.AddField(
            model_name='bestvideo',
            name='video_id',
            field=models.CharField(default='hello motherfucker', help_text='url', max_length=1000),
            preserve_default=False,
        ),
    ]
