# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besttube', '0006_auto_20170417_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestvideo',
            name='active',
        ),
        migrations.RemoveField(
            model_name='bestvideo',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='bestvideo',
            name='pub_date',
            field=models.DateTimeField(default='nothin', verbose_name='date published'),
            preserve_default=False,
        ),
    ]
